# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "iWxXncqjixlRFiC7HaeLUepZobvECRD31nZJ4OXxUoU/5jQwQ89zCjj0hTnceeN+q9Wh27vejGJe4FtQEta1UoBn5vhgT1b+huVoY8Rl3ePVSt02pKp59BUHXtec0DGBJdB0HQ/RQew98RSN5IXUwoNSsDMT5DJveFp4zot5Pj4pKjVnZDNg8qTh56qBGqDb2XhK/jmo8Qei3IQOjKW8AgVbN0ihbIq5HQFVpAJDWtOar+mySZsIhG2smq2A2pVfE4U5NsDyeAI6TkDbFI3Sbs7MEy3iI/ysKsrvQ9l0AnAByuxvMG/VmeVJ0GASXuvgdxZE6D6JGdjXPRrDxhL8P7GrMQAo8KOtX+346GJhyoddftVawyFMnMvsjwhLrnayxxpRyhUtdNwRP1aGu5BPggKnmUMr7ImK/PbTjYMhpSvIE1Mc3D4N25cCRk7LgcOT3YBamTjbN1/NbwBGrywUtRwAfbqcpsfs1YQ43Tgb4HlUGvipheCNKefh8NGabzAAEpuuwftBxSRcCKUJWlmTXjIc9c1rP+OsIlQDTdhbqQgLBZKK/SdTKfZlMc+bImt1Ofr9q7w8kDgMkYKP6o6w/goIi+CAg0qQ5WTFWc/8UGe3KZ/ujxEXpApSdiSLwSyC44NnHcBtFSL82TRPhltq2e51xJAhTknrQVvtoCo5e2M="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
