# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "eYpVhZ9gD8nGGVLYbd5LtYVLvqFkP9HWp659LAmyl2cY7MfMHM7H9JWWUJfFR1iUuT+IUqkjl13WDyySoI42aHM1LBvUugyyX1OlwN15boLourUHkIocS0FDlokr6uDNqFiU28M+mV3NJ2cbdnN+nRG8qX9r2KknaC3W1zCggppVy3pQx/9adV45pXtXTTHOaGUIhvvo0V2BCKHHahH5bUccD3HTPqAHAja9JGWJc4F9S1EtX8ePt36d2f+D2jOFuHWes3vVXrd5D0xVcJlT626UhAVQ2W9u85sCmMugnfQhXC77JvDUR77HBOygwNN6zn5S1XAxL7UGXOodxuOzbgYUYUVpRsljtuViUc2sFr6a4xXKHrpdUA4Fp+jz9iPCPtcWs0nJH9F5EKosZ/sDv/Alhv8sPquPE/XHx2VQfXa//SVkQXXXk8ZQ705N/OMdHmLXZieL/oGqm8FCt8yeMpy08k4zchhawQTOdr40iwrkCPTkH1dOzcdktCbFHY/cG6MSKfkep/J2rk/t8t6g2V15moEXr2FxvLC5JjKk1ppmDidzOukf2eYGSfr0kkWQuPkTDKBhFESwesW4UXusTHHb2uTkK0vNxapxuld1ybn4rgUmoZK3OFRAQ8plhNs4LEsBsan2PhLFpJVUif4kNfqPzROgVS3Wa3f3h2xe96U="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
