# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "iWxXncqjixlRFiC7HaeLUepZobvECRD31nZJ4OXxUoU/5jQwQ89zCjj0hTnceeN+q9Wh27vejGJe4FtQEta1UoBn5vhgT1b+huVoY8Rl3ePVSt02pKp59BUHXtec0DGBJdB0HQ/RQew98RSN5IXUwoNSsDMT5DJveFp4zot5Pj4pKjVnZDNg8qTh56qBGqDb2XhK/jmo8Qei3IQOjKW8AgVbN0ihbIq5HQFVpAJDWtOar+mySZsIhG2smq2A2pVfE4U5NsDyeAI6TkDbFI3Sbs7MEy3iI/ysKsrvQ9l0AnAByuxvMG/VmeVJ0GASXuvgdxZE6D6JGdjXPRrDxhL8P7GrMQAo8KOtX+346GJhyoddftVawyFMnMvsjwhLrnayxxpRyhUtdNwRP1aGu5BPggKnmUMr7ImK/PbTjYMhpSvIE1Mc3D4N25cCRk7LgcOT3YBamTjbN1/NbwBGrywUtRwAfbqcpsfs1YQ43Tgb4HlUGvipheCNKefh8NGabzAAEpuuwftBxSRcCKUJWlmTXjIc9c1rP+OsIlQDTdhbqQgLBZKK/SdTKfZlMc+bImt1Ofr9q7w8kDgMkYKP6o6w/goIi+CAg0qQ5WTFWc/8UGe3KZ/ujxEXpApSdiSLwSyC44NnHcBtFSL82TRPhltq2e51xJAhTknrQVvtoCo5e2M="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
