travis:
  secure:
    BINSTAR_TOKEN: tf2oLQLgFmoCo4b+wZoYftV+ONDWprhUTT+z2z6ScOyxI5wBgXG8WJPl1yAooZmXK716aQMFu9hM4YrGds79huy1jaKGo21fJ/mK4kk0RYwicEIu/o8DnHhdVFzVWD0V6aGkMsiPQqN3hiVLj+tw0L06siApeRFu/aNbvgMB7imV6zmD8vkpfKPAj+hhQh4msYQAa3EMSqvANeZVGueOAtFDFergGOLVKZXdIy33YbOAZ75RRsC/olCwrsryH1k/8SyhDp5EUDuHCj8oLQ0ThquE+39K6cikSCcM9hm7Mrvv4oOE8cKtqg0ce5aDhCpSpKsKpaQ0MoIZQ+hQ7yBESSph5GzOSyIBJ6oj4HWb0ZOBt6YJ2G5se3NBJHPlEXPIJwxZeaILR7IuZXV9YAfnMNZioDuH6Q/6QxgDs6fkmk66lW7qvJWW1m0vj2gRSGIdQ+g0sRG1/Gn8et7YpSi318BVBXijNpA8XCJDzcygtvfHwkh8KIga5fZxgD+XVGPRnG6o86kKfFAo25aYdNYQELez/yUZ1B1xaKH6C8tf3SHedpLgsn2F0pWRVl0wZQSlFaDuT/CohKHFDJOfzVnAQiq0EAcNfukh98tA8w+cHGx44Snh22Bu4BpW4Y00J2RHmpDh/mNInrDQXcAM67phN1VBw0o8ZCyGtQhFXBq7q3w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
