travis:
  secure:
    BINSTAR_TOKEN: eYpVhZ9gD8nGGVLYbd5LtYVLvqFkP9HWp659LAmyl2cY7MfMHM7H9JWWUJfFR1iUuT+IUqkjl13WDyySoI42aHM1LBvUugyyX1OlwN15boLourUHkIocS0FDlokr6uDNqFiU28M+mV3NJ2cbdnN+nRG8qX9r2KknaC3W1zCggppVy3pQx/9adV45pXtXTTHOaGUIhvvo0V2BCKHHahH5bUccD3HTPqAHAja9JGWJc4F9S1EtX8ePt36d2f+D2jOFuHWes3vVXrd5D0xVcJlT626UhAVQ2W9u85sCmMugnfQhXC77JvDUR77HBOygwNN6zn5S1XAxL7UGXOodxuOzbgYUYUVpRsljtuViUc2sFr6a4xXKHrpdUA4Fp+jz9iPCPtcWs0nJH9F5EKosZ/sDv/Alhv8sPquPE/XHx2VQfXa//SVkQXXXk8ZQ705N/OMdHmLXZieL/oGqm8FCt8yeMpy08k4zchhawQTOdr40iwrkCPTkH1dOzcdktCbFHY/cG6MSKfkep/J2rk/t8t6g2V15moEXr2FxvLC5JjKk1ppmDidzOukf2eYGSfr0kkWQuPkTDKBhFESwesW4UXusTHHb2uTkK0vNxapxuld1ybn4rgUmoZK3OFRAQ8plhNs4LEsBsan2PhLFpJVUif4kNfqPzROgVS3Wa3f3h2xe96U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
