travis:
  secure:
    BINSTAR_TOKEN: iWxXncqjixlRFiC7HaeLUepZobvECRD31nZJ4OXxUoU/5jQwQ89zCjj0hTnceeN+q9Wh27vejGJe4FtQEta1UoBn5vhgT1b+huVoY8Rl3ePVSt02pKp59BUHXtec0DGBJdB0HQ/RQew98RSN5IXUwoNSsDMT5DJveFp4zot5Pj4pKjVnZDNg8qTh56qBGqDb2XhK/jmo8Qei3IQOjKW8AgVbN0ihbIq5HQFVpAJDWtOar+mySZsIhG2smq2A2pVfE4U5NsDyeAI6TkDbFI3Sbs7MEy3iI/ysKsrvQ9l0AnAByuxvMG/VmeVJ0GASXuvgdxZE6D6JGdjXPRrDxhL8P7GrMQAo8KOtX+346GJhyoddftVawyFMnMvsjwhLrnayxxpRyhUtdNwRP1aGu5BPggKnmUMr7ImK/PbTjYMhpSvIE1Mc3D4N25cCRk7LgcOT3YBamTjbN1/NbwBGrywUtRwAfbqcpsfs1YQ43Tgb4HlUGvipheCNKefh8NGabzAAEpuuwftBxSRcCKUJWlmTXjIc9c1rP+OsIlQDTdhbqQgLBZKK/SdTKfZlMc+bImt1Ofr9q7w8kDgMkYKP6o6w/goIi+CAg0qQ5WTFWc/8UGe3KZ/ujxEXpApSdiSLwSyC44NnHcBtFSL82TRPhltq2e51xJAhTknrQVvtoCo5e2M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
