travis:
  secure:
    BINSTAR_TOKEN: Hn3Hq//FIFXoAbONy/Pk2fInv1X9+LfQ7N1MrYm028DIu3t0+qvr1EGHKNj5F43htorsTuHLWyyHHL1m+Aow96GNVdeP9U4vKkrfwb2awpy2+2dEg7AllTbg3FVpqP+VbJS2z+xUY0qB6jbkB3K6peqpOrEUC421I5yUJLNyZBXoO1J+nQJje15WBQOd42iT5NVfcTWetclDE9jsCR5WdMF2VxZTETXXZloEjxVajksGtt6klQQ9Ha8u9Tjsv5YSNPiKUWXUxShDnDtkamWw6Ph7xU4ahtqV0mcW6X/l28+lF+7WEzdBWKI4ZLVf8vvkIr1F5SobJVctkG97NI6HAXb0mdCyHo27owSGDTR7mxKLWxMnBuUP4+NNYT0ZdfKookRGC2bqgREQiwBQTKQQXWHZPCwPMnqSK5vTOoi+G44cpKVUzc6nj75aWy2nitCeFgqrnw32LVYXa1FpqFupAeSfDpzVhQrXvzoUvz59W5XQtqr7JZNXCp/N3XNcv/BK/7pdIlGJ1A1assblnQAV2nNbnJFYMNhqt7r6UmpiNLnz7vM3FHj61WfrkBSrtPMHd2Gc+FwbZE/TF40LQXIPacl8wd/WAZ439BiJHap3J6ubn8GiorS6vz2WYUwyTwmz6mUmY08LG9L3VmE39/lS30hdkQMsMrHibk63x1s3rtg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
