travis:
  secure:
    BINSTAR_TOKEN: AlB1kpjlepA47P9ZIWUYJgORshkFv7aN0GubGjUbzSGJvQGQgGcqqUdjPiiJUqlFNx+qQwFF+eh0YAMYm9UHszi7KSGyHUJebU3dBxLUiJkS2eQcNanObp1SIH3rGdmo5KfAXU2urs+lNG1TNXiQFeViqmODS6ad5L43sumkOvJREil3ZEAfJ/Ophhkpj2yKtQnVSwRsOhvwWnkszQ5H6XZliYqEM2DwLF84BcvKe7w17rF5TTND5Wlccct3V/OG+Yb7rwFDc+4Xm7stEwAV92VzkDmn9eS9UnGrCdA32EVZimXwhc1bKeydJip9p3MY+pChuwJj0yqZOLQuYibBffFhSvlTZiax/CSWyYa5nd4HbbbsnZxYMVTrT1uHOLaLvo/bMHyuYTAFf4J1W/4zP0QXIdYq8w8r3/VMTSn8vvIh5kgY+eLpIDyIMvg2FHH4ILZba8SiynHiFFWk2kymXumv8EQDrKfJwHbS+xvVrnHwvmSFTBVU0CsGad+vXLuEYu9XfFJvu8xM1ULsJP3TT0iJSir0vN+XLtFa1c8GJQoVr+0Hh5xQSnJzXiijlj21eZfjND83Hn/qbUdJEXServNdWU4v/LL4J0JrMNyV9DRw1O0XcJNvd31IpmkMHYm7tjHX+3HaY3Bne3os2cjo3Jtirxs87gA8azwNMjoD6N8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
